// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaeqSZ-FWP9H7EYllqEfwUk5yfaf_kpzA',
    appId: '1:490701818421:web:6955359f735f9980bf7f7c',
    messagingSenderId: '490701818421',
    projectId: 'diplom-9c560',
    authDomain: 'diplom-9c560.firebaseapp.com',
    storageBucket: 'diplom-9c560.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduUtUpSGEDaP1brY1mETot3i5uzhPibA',
    appId: '1:490701818421:android:dfb5fc0a284989a9bf7f7c',
    messagingSenderId: '490701818421',
    projectId: 'diplom-9c560',
    storageBucket: 'diplom-9c560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKjbaEu5MV6VbrlteqSGw8epoBZfJKMs',
    appId: '1:490701818421:ios:c0b4c8817aa408c9bf7f7c',
    messagingSenderId: '490701818421',
    projectId: 'diplom-9c560',
    storageBucket: 'diplom-9c560.appspot.com',
    iosClientId: '490701818421-a6fbre6uvf76of2kjoe02i2543c14k2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydiplom',
  );
}
